import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// ------------------------------------------------------------------
// 📁 components/Footer.js から Footer コンポーネントをインポートします
import Footer from '../components/Footer'; 
import Header from '../components/Header';
// ------------------------------------------------------------------

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children} {/* 各ページのコンテンツがここに表示されます */}
        {/* ------------------------------------------------------ */}
        <Footer /> {/* 全てのページに共通のフッターを追加します */}
        {/* ------------------------------------------------------ */}
      </body>
    </html>
  );
}